server:
  port: ${PORT_CLIENT_OAUTH2}

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_CONF_URI}
      profile: ${CONFIG_SERVER_PROFILE}
      enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}