server:
  port: ${PORT_SERVICE_GATEWAY}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clientes
              uri: lb://msvc-cliente
              predicates:
                - Path=/api/cliente/**
            - id: compras
              uri: lb://msvc-compras
              predicates:
                - Path=/api/compra/**

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
