server:
  port: ${PORT_SERVICE_GATEWAY}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clientes
              uri: lb://msvc-cliente
              predicates:
                - Path=/api/cliente/**

            - id: compras
              uri: lb://msvc-compras
              predicates:
                - Path=/api/compra/**

logging:
  level:
    root: INFO
    com.irojas.microservices: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/cloud-gateway.log
    max-size: 10MB
    max-history: 30
