spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_CONF_URI:http://localhost:9000}       # ← lee la variable de entorno
      profile: ${CONFIG_SERVER_PROFILE:dev}
      enabled: true
  data:
    mongodb:
      uri: ${BD_MONGODB_URI:mongodb://localhost:27017/venta_db}  # ← fallback para desarrollo local

server:
  port: ${PORT_SERVICE_COMPRAS:7020}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}  # ← lee la variable
